services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strongpassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  atena-backend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atena-backend
    depends_on: 
      - postgres
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./:/app

volumes:
  postgres: